#!/usr/bin/env python3
"""extract_rogue_assets.py -- ca65 .byte tables -> C arrays for mac-rogue.

The Macintosh port reuses the *exact* pixel data of the Apple-1 / TMS9918
original (POM1 `sketchs/tms9918/game_rogue`) so the two builds are visually
identical. Rather than transcribing 2.6 KB of hex by hand, this script slices
the three source tables straight out of the 6502 sources:

  tileset_rogue.inc   `tileset_rogue`       2048 B  256 chars x 8 rows, 1 bpp
                      `tileset_color_table`   32 B  fg/bg nibble per 8 chars
  TMS_Rogue.asm       `sprite_pats`          448 B  14 sprites x 32 B (16x16)
  sprites_boss.asm    `boss_sprite_pats`     128 B  4 quadrants of the demon

Output: rogue_gfx.c + rogue_gfx.h next to the C sources.

Run from anywhere:  python3 tools/extract_rogue_assets.py
Re-run whenever the POM1 artwork changes; the file is generated, do not edit.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEST = HERE.parent
# POM1 lives beside POM68K in the same src/ tree.
POM1 = HERE.parents[3] / "POM1"
ROGUE = POM1 / "sketchs" / "tms9918" / "game_rogue"

BYTE_RE = re.compile(r"^\s*\.byte\s+(.*?)(?:\s*;.*)?$")


def parse_bytes(lines):
    """Collect every $XX literal from a run of ca65 `.byte` directives."""
    out = []
    for line in lines:
        m = BYTE_RE.match(line)
        if not m:
            continue
        for tok in m.group(1).split(","):
            tok = tok.strip()
            if not tok:
                continue
            if tok.startswith("$"):
                out.append(int(tok[1:], 16))
            elif tok.isdigit():
                out.append(int(tok))
            else:
                raise ValueError("unexpected .byte operand: %r" % tok)
    return out


def slice_label(path, start_label, stop_pred):
    """Return the .byte payload following `start_label:` up to stop_pred."""
    lines = path.read_text().splitlines()
    for i, line in enumerate(lines):
        if line.strip().startswith(start_label + ":"):
            break
    else:
        raise SystemExit("label %s not found in %s" % (start_label, path))
    body = []
    for line in lines[i + 1:]:
        if stop_pred(line):
            break
        body.append(line)
    return parse_bytes(body)


def emit(f, name, data, per_line, comment):
    f.write("/* %s */\n" % comment)
    f.write("const unsigned char %s[%d] = {\n" % (name, len(data)))
    for off in range(0, len(data), per_line):
        chunk = data[off:off + per_line]
        f.write("    " + ", ".join("0x%02X" % b for b in chunk) + ",\n")
    f.write("};\n\n")


def main():
    if not ROGUE.is_dir():
        raise SystemExit("POM1 rogue sources not found at %s" % ROGUE)

    inc = ROGUE / "tileset_rogue.inc"
    asm = ROGUE / "TMS_Rogue.asm"
    boss = ROGUE / "sprites_boss.asm"

    # The pattern table runs until the colour-table banner comment.
    tiles = slice_label(inc, "tileset_rogue",
                        lambda l: "tileset_color_table" in l)
    colors = slice_label(inc, "tileset_color_table", lambda l: False)
    # sprite_pats runs to the prng16 include banner at the tail of the file.
    sprites = slice_label(asm, "sprite_pats",
                          lambda l: "prng16 --" in l)
    bosspats = slice_label(boss, "boss_sprite_pats", lambda l: False)

    checks = [("tileset", tiles, 2048), ("colour table", colors, 32),
              ("sprite_pats", sprites, 448), ("boss", bosspats, 128)]
    for label, data, want in checks:
        if len(data) != want:
            raise SystemExit("%s: got %d bytes, expected %d"
                             % (label, len(data), want))
        print("  %-14s %4d B  ok" % (label, len(data)))

    hdr = DEST / "rogue_gfx.h"
    src = DEST / "rogue_gfx.c"

    hdr.write_text(
        "/* rogue_gfx.h -- GENERATED by tools/extract_rogue_assets.py.\n"
        " * Pixel data lifted verbatim from the POM1 TMS9918 build so the\n"
        " * Macintosh port renders the same dungeon. Do not edit by hand.\n"
        " */\n"
        "#ifndef ROGUE_GFX_H\n"
        "#define ROGUE_GFX_H\n"
        "\n"
        "/* 256 chars x 8 rows, 1 bpp, MSB = leftmost pixel. */\n"
        "extern const unsigned char kTileset[2048];\n"
        "/* One fg/bg byte per group of 8 chars (fg = high nibble). */\n"
        "extern const unsigned char kTileColors[32];\n"
        "/* 14 sprites x 32 B. Quadrant order: TL, BL, TR, BR (8 rows each). */\n"
        "extern const unsigned char kSpritePats[448];\n"
        "/* The depth-13 demon: 4 more 16x16 slots, same quadrant order. */\n"
        "extern const unsigned char kBossPats[128];\n"
        "\n"
        "#endif /* ROGUE_GFX_H */\n")

    with src.open("w") as f:
        f.write("/* rogue_gfx.c -- GENERATED by tools/extract_rogue_assets.py.\n"
                " * Artwork: Quale's SCROLL-O-SPRITES (CC-BY-3.0) sliced by\n"
                " * POM1's extract_quale_8x8_tiles.py, plus Hexany Ives'\n"
                " * Monster Menagerie creature_024 (CC0) for the boss.\n"
                " * Do not edit by hand -- re-run the extractor.\n"
                " */\n"
                '#include "rogue_gfx.h"\n\n')
        emit(f, "kTileset", tiles, 8,
             "Pattern table: char N occupies bytes N*8 .. N*8+7.")
        emit(f, "kTileColors", colors, 16,
             "Colour table: entry N covers chars N*8 .. N*8+7.")
        emit(f, "kSpritePats", sprites, 8,
             "Sprite patterns, slot S at byte offset S*8 (S = SAT name byte).")
        emit(f, "kBossPats", bosspats, 8,
             "Boss quadrants, continuing the sprite slot space at name 56.")

    print("wrote %s and %s" % (src.name, hdr.name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
