/* rogue_gfx.h -- GENERATED by tools/extract_rogue_assets.py.
 * Pixel data lifted verbatim from the POM1 TMS9918 build so the
 * Macintosh port renders the same dungeon. Do not edit by hand.
 */
#ifndef ROGUE_GFX_H
#define ROGUE_GFX_H

/* 256 chars x 8 rows, 1 bpp, MSB = leftmost pixel. */
extern const unsigned char kTileset[2048];
/* One fg/bg byte per group of 8 chars (fg = high nibble). */
extern const unsigned char kTileColors[32];
/* 14 sprites x 32 B. Quadrant order: TL, BL, TR, BR (8 rows each). */
extern const unsigned char kSpritePats[448];
/* The depth-13 demon: 4 more 16x16 slots, same quadrant order. */
extern const unsigned char kBossPats[128];

#endif /* ROGUE_GFX_H */
