#!/usr/bin/env python3
# POM68K — Macintosh 68k emulator
# VERHILLE Arnaud — Copyright (C) 2026 — GPLv3 (see LICENSE)
#
# Generates src/MacSymbolTables.inc — the A-line trap names and low-memory
# global names the debugger annotates with — from cxmon, the monitor that
# ships with Basilisk II (github.com/cebix/macemu, cxmon/src/mon_atraps.h
# and cxmon/src/mon_lowmem.cpp, (C) 1997-2004 Christian Bauer and Marc
# Hellwig, GPL v2 or later). Names and numbers are taken as they are; where
# one trap word carries two names, the first in cxmon's order is kept and
# the dropped one is listed in the output's header.
#
#   python3 tools/gen_mac_symbols.py ~/src/macemu > src/MacSymbolTables.inc
import re
import subprocess
import sys
from pathlib import Path

ENTRY = re.compile(r'\{"([^"]+)"\s*,\s*0x([0-9A-Fa-f]+)\}')


def entries(path):
    return [(name, int(v, 16)) for name, v in ENTRY.findall(path.read_text())]


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_mac_symbols.py <macemu checkout>")
    root = Path(sys.argv[1])
    src = root / "cxmon" / "src"
    commit = subprocess.run(["git", "-C", str(root), "log", "-1", "--format=%H",
                             "--", "cxmon/src/mon_atraps.h",
                             "cxmon/src/mon_lowmem.cpp"],
                            capture_output=True, text=True, check=True).stdout.strip()
    traps, dropped, seen = [], [], set()
    for name, word in entries(src / "mon_atraps.h"):
        if word in seen:
            dropped.append((name, word))
            continue
        seen.add(word)
        traps.append((word, name))
    traps.sort()
    low = sorted((a, n) for n, a in entries(src / "mon_lowmem.cpp"))

    out = sys.stdout
    out.write("// GENERATED by tools/gen_mac_symbols.py - do not edit.\n")
    out.write("// Source: cxmon (Basilisk II's monitor), https://github.com/cebix/macemu\n")
    out.write(f"//   commit {commit}\n")
    out.write("//   cxmon/src/mon_atraps.h, cxmon/src/mon_lowmem.cpp\n")
    out.write("//   (C) 1997-2004 Christian Bauer, Marc Hellwig - GPL v2 or later.\n")
    for name, word in dropped:
        out.write(f"// Second name for ${word:04X} not kept: {name}\n")
    out.write("\n// A-line trap words, ascending.\n")
    out.write("inline constexpr MacTrapName kMacTraps[] = {\n")
    for word, name in traps:
        out.write(f"    {{0x{word:04X}, \"{name}\"}},\n")
    out.write("};\n\n// Low-memory globals, ascending.\n")
    out.write("inline constexpr MacLowMemName kMacLowMem[] = {\n")
    for addr, name in low:
        out.write(f"    {{0x{addr:04X}, \"{name}\"}},\n")
    out.write("};\n")


if __name__ == "__main__":
    main()
