#!/usr/bin/env python3
"""Generate STATUS.md — the gate registry as an artifact, not as prose.

Why this exists
---------------
The registry's sizes used to be hand-typed into four documents, and on
2026-08-28 all four carried a wrong per-host total while the per-label
figures beside them were right (`CHANGELOG.md` 2026-08-28 (eleventh)).
`docs_test` could hold the prose to the roster, but holding is not the same
as writing: TODO.md § 10 wave 3 names the fix — generate the numbers once,
from the files CMake already writes at configure time, and let `docs_test`
verify the artifact instead of chasing sentences.

Inputs (all written by CMake into the build directory):
  pom68k_gates.tsv          registered gates + their labels, this host
  pom68k_gates_absent.tsv   union gates this host cannot register
  pom68k_gate_manifest.tsv  assets/host/scope/tier/slots per gate, this host

The registry has MORE THAN ONE size (the native-backend locksteps register
only on their own host), so STATUS.md is split the same way the checks are:

  * the UNION section is derivable identically on every host (the absent
    roster is added back) and is regenerated by whoever runs the tool;
  * each `## Registered on <host>` section is owned by the host it names
    and preserved verbatim when another host regenerates — the same
    division of labour as `gate_resource_budgets.tsv`.

Runs are recorded, never derived: `--record-run` appends one row from a
`LastTest.log` using `gate_execution_census.py`'s executed/soft-skipped
pair. Copy the log the moment a run ends — every ctest invocation
overwrites it, including a one-gate `ctest -R`.

    tools/status_md.py                          # regenerate from build/
    tools/status_md.py --build-dir build-pgo
    tools/status_md.py --record-run --log saved.log --note "full tier"
"""

import argparse
import os
import platform
import re
import sys

sys.dont_write_bytecode = True   # keep tools/ free of __pycache__
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gate_execution_census import census  # noqa: E402

MARKER = "GENERATED FILE — do not edit by hand"

# Labels carrying a '-'-suffixed policy dimension are per-host manifest
# facts; they live in the per-host tables, not the union one.
POLICY_PREFIXES = ("asset-", "host-", "scope-", "tier-")

# The two hosts that carry the project's proof today. A third architecture
# gets its section the first time the tool runs there.
KNOWN_HOSTS = ("aarch64", "x86_64")


def normalize_host():
    """Mirror Pom68kJitGates.cmake's POM68K_PERF_HOST normalization."""
    m = platform.machine().lower()
    if m in ("arm64", "aarch64"):
        return "aarch64"
    if m in ("x86_64", "amd64"):
        return "x86_64"
    return "other"


def read_labelled(path):
    """name -> [labels] from a `name\\tlabel,label` file (labels may be empty)."""
    out = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if "\t" not in line:
                continue
            name, labels = line.split("\t", 1)
            out[name] = [l for l in labels.split(",") if l]
    return out


def read_manifest(path):
    """name -> {assets, host, scope, tier, slots, slots_src}."""
    out = {}
    with open(path, encoding="utf-8") as f:
        header = f.readline().rstrip("\n").split("\t")
        for line in f:
            cells = line.rstrip("\n").split("\t")
            if len(cells) == len(header):
                out[cells[0]] = dict(zip(header[1:], cells[1:]))
    return out


def count_label(union, label):
    """How many gates `ctest -L <label>` selects: -L is a regex over each
    label, so `jit` also selects `jit-fast` — same rule as docs_test."""
    return sum(1 for labels in union.values()
               if any(label in l for l in labels))


def union_table(union):
    vocab = sorted({l for labels in union.values() for l in labels
                    if not l.startswith(POLICY_PREFIXES)})
    rows = [f"| `{label}` | {count_label(union, label)} |" for label in vocab]
    return "\n".join(["| `ctest -L` | selects |", "|---|---|"] + rows)


def host_section(host, gates, absent, manifest):
    absent_names = ", ".join(f"`{n}`" for n in sorted(absent)) or "—"
    lines = [
        f"{len(gates)} gates registered; {len(absent)} union gates cannot "
        f"register here: {absent_names}.",
        "",
        "| dimension | value | gates |",
        "|---|---|---|",
    ]
    for dim in ("assets", "host", "scope", "tier", "slots_src"):
        counts = {}
        for cells in manifest.values():
            counts[cells[dim]] = counts.get(cells[dim], 0) + 1
        for value in sorted(counts):
            lines.append(f"| {dim} | {value} | {counts[value]} |")
    slots = sum(int(c["slots"]) for c in manifest.values())
    lines += [
        "",
        f"Scheduling cost if every gate ran at once: {slots} slots of "
        "256 MiB (`slots_src` says which rows are measured — an `assumed` "
        "gate is scheduled as one slot because nobody has measured it here).",
    ]
    return "\n".join(lines)


def parse_sections(text):
    """heading line (without '## ') -> body, in file order."""
    sections = {}
    current, body = None, []
    for line in text.splitlines():
        if line.startswith("## "):
            if current is not None:
                sections[current] = "\n".join(body).strip("\n")
            current, body = line[3:], []
        elif current is not None:
            body.append(line)
    if current is not None:
        sections[current] = "\n".join(body).strip("\n")
    return sections


RUN_HEADER = "| start | host | in log | executed | soft-skipped | failed | note |"


def existing_run_rows(sections):
    body = sections.get("Recorded runs", "")
    rows = [l for l in body.splitlines()
            if l.startswith("| ") and l != RUN_HEADER
            and not re.match(r"^\|[-| ]+\|$", l)]
    return rows


def record_run(log_path, host, note):
    with open(log_path, encoding="utf-8", errors="replace") as f:
        text = f.read()
    rows = census(text)
    if not rows:
        sys.exit(f"error: {log_path} contains no gate output — overwritten "
                 f"by a later ctest -R run?")
    start = ""
    m = re.search(r"^Start testing: (.*)$", text, re.M)
    if m:
        start = m.group(1).strip()
    executed = sum(1 for r in rows if r[1] == "executed")
    skipped = sum(1 for r in rows if r[1] == "skipped")
    failed = sum(1 for r in rows if r[1] == "failed")
    note = note.replace("|", "\\|")  # a bare pipe would split the table row
    return (f"| {start} | {host} | {len(rows)} | {executed} | {skipped} "
            f"| {failed} | {note} |")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument("--build-dir", default=os.path.join(root, "build"))
    ap.add_argument("--output", default=os.path.join(root, "STATUS.md"))
    ap.add_argument("--record-run", action="store_true",
                    help="append one row to Recorded runs from a LastTest.log")
    ap.add_argument("--log", help="a preserved LastTest.log (default: the "
                                  "build directory's current one)")
    ap.add_argument("--note", default="",
                    help="free text for the recorded run's note column")
    args = ap.parse_args()

    host = normalize_host()
    gates = read_labelled(os.path.join(args.build_dir, "pom68k_gates.tsv"))
    absent = read_labelled(
        os.path.join(args.build_dir, "pom68k_gates_absent.tsv"))
    manifest = read_manifest(
        os.path.join(args.build_dir, "pom68k_gate_manifest.tsv"))
    if not gates:
        sys.exit(f"error: no gates in {args.build_dir}/pom68k_gates.tsv — "
                 f"configure first")
    if set(manifest) != set(gates):
        sys.exit("error: manifest and roster disagree on the gate set — "
                 "stale configure?")
    union = dict(gates)
    union.update(absent)

    old = {}
    run_rows = []
    if os.path.exists(args.output):
        with open(args.output, encoding="utf-8") as f:
            old = parse_sections(f.read())
        run_rows = existing_run_rows(old)
    if args.record_run:
        log = args.log or os.path.join(args.build_dir, "Testing",
                                       "Temporary", "LastTest.log")
        run_rows.append(record_run(log, host, args.note))

    hosts = sorted(set(KNOWN_HOSTS) | {host})
    host_bodies = []
    for h in hosts:
        heading = f"Registered on {h}"
        if h == host:
            body = host_section(h, gates, absent, manifest)
        elif heading in old:
            body = old[heading]
        else:
            body = (f"_Not yet generated on an {h} host — run "
                    f"`tools/status_md.py` there._")
        host_bodies.append(f"## {heading}\n\n{body}")

    runs = "\n".join([RUN_HEADER, "|---|---|---|---|---|---|---|"] + run_rows)
    if not run_rows:
        runs += "\n\n_(no run recorded yet)_"

    out = f"""# STATUS — the gate registry, generated

<!-- {MARKER}.
     `tools/status_md.py` rewrites it from the files CMake writes at
     configure time (pom68k_gates.tsv, pom68k_gates_absent.tsv,
     pom68k_gate_manifest.tsv); `docs_test` fails when this file and the
     configured registry disagree. -->

The registry has more than one size: the native-backend locksteps register
only on the host they exercise. The union below is derivable identically on
every host (the absent roster is added back); each *Registered on* section
is owned by the host it names and regenerated there — the same division of
labour as `gate_resource_budgets.tsv`. Recorded runs carry
`tools/gate_execution_census.py`'s executed/soft-skipped pair: quote the
pair, never the green total alone — a soft-skipped gate exited 0 and proved
nothing about the behaviour it names.

## Union across hosts — {len(union)} gates

{union_table(union)}

`-L` is a regex over each label: `jit` also selects `jit-fast`, `etalon`
also selects `etalon-core`. The asset/host/scope/tier dimensions and the
scheduling slots are per-host manifest facts and live in the sections below.

{(chr(10) + chr(10)).join(host_bodies)}

## Recorded runs

Appended by `tools/status_md.py --record-run [--log FILE] [--note TEXT]`.
Copy `LastTest.log` the moment a run ends: every ctest invocation
overwrites it, including a one-gate `ctest -R`.

{runs}
"""
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {args.output}: union {len(union)}, {len(gates)} registered "
          f"on {host}, {len(run_rows)} recorded run(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
