#!/usr/bin/env python3
"""Generate STATUS.md — the gate registry as an artifact, not as prose.

Why this exists
---------------
The registry's sizes used to be hand-typed into four documents, and on
2026-08-28 all four carried a wrong per-host total while the per-label
figures beside them were right (`CHANGELOG.md` 2026-08-28 (eleventh)).
`docs_test` could hold the prose to the roster, but holding is not the same
as writing: CHANGELOG.md 2026-08-29 (ninth) names the fix — generate once,
from the files CMake already writes at configure time, and let `docs_test`
verify the artifact instead of chasing sentences.

Inputs (all written by CMake into the build directory):
  pom68k_gates.tsv          registered gates + their labels, this host
  pom68k_gates_absent.tsv   union gates this host cannot register
  pom68k_gate_manifest.tsv  assets/host/scope/tier/config/slots per gate

The registry has MORE THAN ONE size (the native-backend locksteps register
only on their own host), so STATUS.md is split the same way the checks are:

  * the UNION section is derivable identically on every host (the absent
    roster is added back) and is regenerated by whoever runs the tool;
  * each `## Registered on <host>` section is owned by the host it names
    and preserved verbatim when another host regenerates — the same
    division of labour as `gate_resource_budgets.tsv`.
  * the PRODUCT_LLE section is regenerated only from that opt-in configure;
    its manifest marks the eight extra gates, so the default view can still
    be derived and checked from the larger registry.

Runs are recorded, never derived: `--record-run` appends one row from a
`LastTest.log` using `gate_execution_census.py`'s executed/soft-skipped
pair. Copy the log the moment a run ends — every ctest invocation
overwrites it, including a one-gate `ctest -R`.

    tools/status_md.py                          # regenerate from build/
    tools/status_md.py --build-dir build-pgo
    tools/status_md.py --record-run --log saved.log --note "full tier"
"""

import argparse
import os
import platform
import re
import sys

sys.dont_write_bytecode = True   # keep tools/ free of __pycache__
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gate_execution_census import census  # noqa: E402

MARKER = "GENERATED FILE — do not edit by hand"

# Labels carrying a '-'-suffixed policy dimension are per-host manifest
# facts; they live in the per-host tables, not the union one.
POLICY_PREFIXES = ("asset-", "host-", "scope-", "tier-")

# The two hosts that carry the project's proof today. A third architecture
# gets its section the first time the tool runs there.
KNOWN_HOSTS = ("aarch64", "x86_64")

# PRODUCT_LLE adds these labels to shared default gates as qualification
# metadata. Remove them when deriving the default view from that configure.
PRODUCT_QUALIFICATION_LABELS = {"product", "lle", "a64-oracle"}


def normalize_host(build_dir=None):
    """Name the architecture the configured binaries run as.

    On Apple Silicon, ``platform.machine()`` still reports arm64 while a
    Rosetta build directory targets x86_64. Prefer that explicit single-arch
    CMake setting so regenerating the x64 section does not silently rewrite
    the AArch64 one instead.
    """
    if build_dir:
        cache = os.path.join(build_dir, "CMakeCache.txt")
        try:
            with open(cache, encoding="utf-8", errors="replace") as f:
                cache_text = f.read()
            match = re.search(
                r"^CMAKE_OSX_ARCHITECTURES:[^=]*=([^;\r\n]+)$",
                cache_text, re.M)
            if match:
                target = match.group(1).strip().lower()
                if target in ("arm64", "aarch64"):
                    return "aarch64"
                if target in ("x86_64", "amd64"):
                    return "x86_64"
        except OSError:
            pass
    m = platform.machine().lower()
    if m in ("arm64", "aarch64"):
        return "aarch64"
    if m in ("x86_64", "amd64"):
        return "x86_64"
    return "other"


def read_labelled(path):
    """name -> [labels] from a `name\\tlabel,label` file (labels may be empty)."""
    out = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if "\t" not in line:
                continue
            name, labels = line.split("\t", 1)
            out[name] = [l for l in labels.split(",") if l]
    return out


def read_manifest(path):
    """name -> {assets, host, scope, tier, config, slots, slots_src}."""
    out = {}
    with open(path, encoding="utf-8") as f:
        header = f.readline().rstrip("\n").split("\t")
        for line in f:
            cells = line.rstrip("\n").split("\t")
            if len(cells) == len(header):
                out[cells[0]] = dict(zip(header[1:], cells[1:]))
    return out


def count_label(union, label):
    """How many gates `ctest -L <label>` selects: -L is a regex over each
    label, so `jit` also selects `jit-fast` — same rule as docs_test."""
    return sum(1 for labels in union.values()
               if any(label in l for l in labels))


def union_table(union):
    vocab = sorted({l for labels in union.values() for l in labels
                    if not l.startswith(POLICY_PREFIXES)})
    rows = [f"| `{label}` | {count_label(union, label)} |" for label in vocab]
    return "\n".join(["| `ctest -L` | selects |", "|---|---|"] + rows)


def host_section(host, gates, absent, manifest, include_config=False):
    absent_names = ", ".join(f"`{n}`" for n in sorted(absent)) or "—"
    lines = [
        f"{len(gates)} gates registered; {len(absent)} union gates cannot "
        f"register here: {absent_names}.",
        "",
        "| dimension | value | gates |",
        "|---|---|---|",
    ]
    dimensions = ["assets", "host", "scope", "tier"]
    if include_config:
        dimensions.append("config")
    dimensions.append("slots_src")
    for dim in dimensions:
        counts = {}
        for cells in manifest.values():
            counts[cells[dim]] = counts.get(cells[dim], 0) + 1
        for value in sorted(counts):
            lines.append(f"| {dim} | {value} | {counts[value]} |")
    slots = sum(int(c["slots"]) for c in manifest.values())
    lines += [
        "",
        f"Scheduling cost if every gate ran at once: {slots} slots of "
        "256 MiB (`slots_src` says which rows are measured — an `assumed` "
        "gate is scheduled as one slot because nobody has measured it here).",
    ]
    return "\n".join(lines)


def default_view(gates, manifest):
    """Derive the normal registry from either a normal or PRODUCT_LLE build."""
    product_lle = any(cells.get("config") == "product-lle"
                      for cells in manifest.values())
    names = {name for name, cells in manifest.items()
             if cells.get("config") != "product-lle"}
    default_gates = {
        name: [label for label in labels
               if not product_lle or
               label not in PRODUCT_QUALIFICATION_LABELS]
        for name, labels in gates.items() if name in names
    }
    default_manifest = {name: cells for name, cells in manifest.items()
                        if name in names}
    return default_gates, default_manifest


def product_section(host, gates, absent, manifest):
    union = dict(gates)
    union.update(absent)
    return "\n".join([
        f"Configuration union across hosts: {len(union)} gates.",
        "",
        union_table(union),
        "",
        host_section(host, gates, absent, manifest, include_config=True),
    ])


def parse_sections(text):
    """heading line (without '## ') -> body, in file order."""
    sections = {}
    current, body = None, []
    for line in text.splitlines():
        if line.startswith("## "):
            if current is not None:
                sections[current] = "\n".join(body).strip("\n")
            current, body = line[3:], []
        elif current is not None:
            body.append(line)
    if current is not None:
        sections[current] = "\n".join(body).strip("\n")
    return sections


RUN_HEADER = ("| start | host | configuration | in log | executed | "
              "soft-skipped | failed | note |")


def existing_run_rows(sections):
    body = sections.get("Recorded runs", "")
    rows = [l for l in body.splitlines()
            if l.startswith("| ") and not l.startswith("| start | host |")
            and not re.match(r"^\|[-| ]+\|$", l)]
    migrated = []
    for row in rows:
        # The configuration column became explicit on 2026-09-03. Historical
        # rows all predate PRODUCT_LLE recording and therefore mean default.
        parts = row.split(" | ", 3)
        if len(parts) == 4 and parts[2] not in ("default", "product-lle"):
            row = (f"{parts[0]} | {parts[1]} | default | {parts[2]} | "
                   f"{parts[3]}")
        migrated.append(row)
    return migrated


def record_run(log_path, host, configuration, note):
    with open(log_path, encoding="utf-8", errors="replace") as f:
        text = f.read()
    rows = census(text)
    if not rows:
        sys.exit(f"error: {log_path} contains no gate output — overwritten "
                 f"by a later ctest -R run?")
    start = ""
    m = re.search(r"^Start testing: (.*)$", text, re.M)
    if m:
        start = m.group(1).strip()
    executed = sum(1 for r in rows if r[1] == "executed")
    skipped = sum(1 for r in rows if r[1] == "skipped")
    failed = sum(1 for r in rows if r[1] == "failed")
    note = note.replace("|", "\\|")  # a bare pipe would split the table row
    return (f"| {start} | {host} | {configuration} | {len(rows)} | "
            f"{executed} | {skipped} | {failed} | {note} |")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument("--build-dir", default=os.path.join(root, "build"))
    ap.add_argument("--output", default=os.path.join(root, "STATUS.md"))
    ap.add_argument("--record-run", action="store_true",
                    help="append one row to Recorded runs from a LastTest.log")
    ap.add_argument("--log", help="a preserved LastTest.log (default: the "
                                  "build directory's current one)")
    ap.add_argument("--note", default="",
                    help="free text for the recorded run's note column")
    args = ap.parse_args()

    host = normalize_host(args.build_dir)
    gates = read_labelled(os.path.join(args.build_dir, "pom68k_gates.tsv"))
    absent = read_labelled(
        os.path.join(args.build_dir, "pom68k_gates_absent.tsv"))
    manifest = read_manifest(
        os.path.join(args.build_dir, "pom68k_gate_manifest.tsv"))
    if not gates:
        sys.exit(f"error: no gates in {args.build_dir}/pom68k_gates.tsv — "
                 f"configure first")
    if set(manifest) != set(gates):
        sys.exit("error: manifest and roster disagree on the gate set — "
                 "stale configure?")
    product_lle = any(cells.get("config") == "product-lle"
                      for cells in manifest.values())
    configuration = "product-lle" if product_lle else "default"
    default_gates, default_manifest = default_view(gates, manifest)
    union = dict(default_gates)
    union.update(absent)

    old = {}
    run_rows = []
    if os.path.exists(args.output):
        with open(args.output, encoding="utf-8") as f:
            old = parse_sections(f.read())
        run_rows = existing_run_rows(old)
    if args.record_run:
        log = args.log or os.path.join(args.build_dir, "Testing",
                                       "Temporary", "LastTest.log")
        run_rows.append(record_run(log, host, configuration, args.note))

    hosts = sorted(set(KNOWN_HOSTS) | {host})
    host_bodies = []
    for h in hosts:
        heading = f"Registered on {h}"
        if h == host:
            body = host_section(h, default_gates, absent, default_manifest)
        elif heading in old:
            body = old[heading]
        else:
            body = (f"_Not yet generated on an {h} host — run "
                    f"`tools/status_md.py` there._")
        host_bodies.append(f"## {heading}\n\n{body}")

    product_heading = "PRODUCT_LLE on aarch64"
    if product_lle:
        product_body = product_section(host, gates, absent, manifest)
    elif product_heading in old:
        product_body = old[product_heading]
    else:
        product_body = ("_Not yet generated from a PRODUCT_LLE configure — run "
                        "`tools/status_md.py --build-dir build-product-lle`._")

    runs = "\n".join([RUN_HEADER,
                       "|---|---|---|---|---|---|---|---|"] + run_rows)
    if not run_rows:
        runs += "\n\n_(no run recorded yet)_"

    out = f"""# STATUS — the gate registry, generated

<!-- {MARKER}.
     `tools/status_md.py` rewrites it from the files CMake writes at
     configure time (pom68k_gates.tsv, pom68k_gates_absent.tsv,
     pom68k_gate_manifest.tsv); `docs_test` fails when this file and the
     configured registry disagree. -->

The default registry has more than one size: the native-backend locksteps
register only on the host they exercise. Its union below is derivable
identically on every host (the absent roster is added back); each *Registered
on* section is owned by the host it names and regenerated there — the same
division of labour as `gate_resource_budgets.tsv`. `PRODUCT_LLE` is a distinct,
opt-in configuration: its section records both the shared gates it qualifies
and the gates it alone registers. Recorded runs name their configuration and
carry `tools/gate_execution_census.py`'s executed/soft-skipped pair: quote the
pair, never the green total alone — a soft-skipped gate exited 0 and proved
nothing about the behaviour it names.

## Union across hosts — {len(union)} gates

{union_table(union)}

`-L` is a regex over each label: `jit` also selects `jit-fast`, `etalon`
also selects `etalon-core`. The asset/host/scope/tier dimensions and the
scheduling slots are per-host manifest facts and live in the sections below.

{(chr(10) + chr(10)).join(host_bodies)}

## {product_heading}

{product_body}

## Recorded runs

Appended by `tools/status_md.py --record-run [--log FILE] [--note TEXT]`.
Copy `LastTest.log` the moment a run ends: every ctest invocation
overwrites it, including a one-gate `ctest -R`.

{runs}
"""
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {args.output}: default union {len(union)}, "
          f"{len(default_gates)} default gates registered on {host}, "
          f"configuration {configuration} has {len(gates)}; "
          f"{len(run_rows)} recorded run(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
