# POM68K — guest-side differential oracles: a Retro68 program run under
# POM68K and under MAME on the same prepared image, its report held to
# MAME's recorded one on the fields both models can judge (dev/README.md).

# The Prober in Startup Items of the profile's locked volume reports
# Gestalt, low memory, a bus-error topology, AppleTalk and the device
# inventory (CHANGELOG 2026-10-02 (seventh)); tools/prober_oracle_<mame>.tsv
# is MAME's report on the same prepared image, regenerated by
# tools/prober_oracle.sh. Soft-skips without the ROM, the volume or the
# built Prober.
add_executable(prober_oracle tests/prober_oracle.cpp)
target_link_libraries(prober_oracle PRIVATE pom68k_core)
# The siblings since 2026-10-10: same boards and ROMs, their own MAME
# systems. No LC 575: MAME 0.287's maclc575 ("imperfect") stalls on Starting
# Up, so it has no report to hold POM68K to.
foreach(pair lcii:maclc2 q605:macqd605 lc475:maclc475 q800:macqd800
             q650:macqd650 q610:macqd610 c650:macct650 c610:macct610
             q630:macqd630 lc580:maclc580 q700:macqd700 q900:macqd900)
    string(REPLACE ":" ";" pair "${pair}")
    list(GET pair 0 profile)
    list(GET pair 1 mame)
    add_test(NAME ${profile}_prober_oracle_etalon
             COMMAND prober_oracle ${profile} --check tools/prober_oracle_${mame}.tsv
             WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
    set_tests_properties(${profile}_prober_oracle_etalon PROPERTIES TIMEOUT 600)
endforeach()
