# POM68K — guest-side differential oracles: a Retro68 program run under
# POM68K and under MAME on the same prepared image, its report held to
# MAME's recorded one on the fields both models can judge (dev/README.md).

# The LC II (CHANGELOG 2026-10-02 (seventh)): the
# Retro68 Prober in Startup Items of the locked System 7.1 volume reports
# Gestalt, low memory, a bus-error topology, AppleTalk and the device
# inventory; its report must equal MAME maclc2's on the same prepared image
# (tools/prober_oracle_maclc2.tsv, regenerated by tools/prober_oracle.sh)
# on every field both models can judge. Soft-skips without the ROM, the
# volume or the built Prober (dev/README.md).
add_executable(lcii_prober_oracle tests/lcii_prober_oracle.cpp)
target_link_libraries(lcii_prober_oracle PRIVATE pom68k_core)
add_test(NAME lcii_prober_oracle_etalon
         COMMAND lcii_prober_oracle --check tools/prober_oracle_maclc2.tsv
         WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
set_tests_properties(lcii_prober_oracle_etalon PROPERTIES TIMEOUT 600)
