# POM68K — guest-side differential oracles: a Retro68 program run under
# POM68K and under MAME on the same prepared image, its report held to
# MAME's recorded one on the fields both models can judge (dev/README.md).

# The Prober in Startup Items of the profile's locked volume reports
# Gestalt, low memory, a bus-error topology, AppleTalk and the device
# inventory (CHANGELOG 2026-10-02 (seventh)); tools/prober_oracle_<mame>.tsv
# is MAME's report on the same prepared image, regenerated by
# tools/prober_oracle.sh. Soft-skips without the ROM, the volume or the
# built Prober.
add_executable(prober_oracle tests/prober_oracle.cpp)
target_link_libraries(prober_oracle PRIVATE pom68k_core)
foreach(pair lcii:maclc2 q605:macqd605)
    string(REPLACE ":" ";" pair "${pair}")
    list(GET pair 0 profile)
    list(GET pair 1 mame)
    add_test(NAME ${profile}_prober_oracle_etalon
             COMMAND prober_oracle ${profile} --check tools/prober_oracle_${mame}.tsv
             WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
    set_tests_properties(${profile}_prober_oracle_etalon PROPERTIES TIMEOUT 600)
endforeach()
